# Generated by Django 5.0 on 2023-12-20 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Наименование категории')),
                ('category_description', models.TextField(max_length=100, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Наименование продукта')),
                ('product_description', models.TextField(max_length=100, verbose_name='Описание продукта')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Изображение продукта')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продукта за единицу')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('date_last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения записи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
